name: ovo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  flutter_svg: ^2.0.10+1
  get: 4.6.6
  flutter: 
    sdk: flutter
  styled_widget: ^0.4.1
  pull_to_refresh: ^2.0.0

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Ovo
      fonts:
        - asset: assets/fonts/Ovo/Ovo-Regular.ttf

